### ISSUE TITLE
Test failed with rails 5.2

### ISSUE THREAD

**Issue by alee-ccu** [rails/globalid#112]
Thanks for maintaining globalid.

I am trying to making rails 5.2 available in Debian. During our tests we found this gem fail on tests with rails 5.2:
```
Failure:
RailtieTest#test_SignedGlobalID.verifier_defaults_to_nil_when_secret_token_is_not_present [/home/travis/build/alee-ccu/globalid/test/cases/railtie_test.rb:41]:
Expected #<GlobalID::Verifier:0x00007f7558521b40 @secret="\xE9\xCD\xAB\xCE\xFF\x93v\x14\xF1\a\xE7/\e\xB2<\xE0\xE3\xA5~\r\xC7\xB5\xEB\xC9`PFx\f\x13\x04vs\x95\xDB\xB1`U\x8FM^(\x7FQ\x7F\xED\xE7U;\xF8r\xB7\x87\xF6\xC8;o\xE7\xBB\xCC\x8E\xFB\xE6\x94", @digest="SHA1", @serializer=Marshal, @options={}, @rotations=[]> to be nil.
```

 I also reproduced the failed tests on `travis-ci.org` with both version `0.4.1` and `master` branch, please see the full log at:
 https://travis-ci.org/alee-ccu/globalid/jobs/464195985
 https://travis-ci.org/alee-ccu/globalid/jobs/464202126

**Comment by y-yagi** [comment]
Thanks for your report. I fixed with #113. Thanks.
