### ISSUE TITLE
suggestion - class method to create globalid from values

### ISSUE THREAD

**Issue by antulik** [rails/globalid#59]
Would like to suggest to add class method like `GlobalID.create` but where you can pass `model_class` and `model_id` directly. 

This is helpful when you need to create GlobalID without object, for example in polymorphic associations where you have two columns with `class` and `id` (like owner_type and owner_id)

for example

```ruby
GlobalID.create('User', 4, options)
```

alternatively currently we have to do 

```ruby
User.new(id: 4).to_global_id
```

which results in unnecessary object creation

**Comment by kaspth** [comment]
For what you're trying to solve, your solution is too low of an abstraction for my taste.

But I'd love to improve how Global ID and polymorphic associations work together.

Can you elaborate on what the polymorphic associations and your query looks like?

**Comment by antulik** [comment]
I would split discussion into two parts: the first is having flexible constructor and second polymorphic association. 

Custom constructor is for extra flexibility, pretty much for all custom use-cases falling outside standard model.to_global_id 

Polymorphic wise. Our simplified example, we have `Product` and `Post` models. They can be favourited with model `Favourite`. So Favourite model has (content_type, content_id). On favourites screen we need a list of favourites with links to `Share` screen, where you can share `Product` or `Post`. So we need `favourite.content.to_global_id` to be included in links. But there is no point of fetching all models as we only need `model_name` and `model_id` for global id.

**Comment by meinac** [comment]
+1 for class method which creates global id for given attributes like
```ruby
GlobalID.create('Model', 1, {})
```

**Comment by cristianbica** [comment]
I guess this is useful when trying to get a GID for belongs_to relation without a trip to the db. We can hook into the relation object and the usage will be: User.find(42).company.gid <- this will make only one trip to the db to find the user with ID 42

**Comment by kaspth** [comment]
I still feel this would be better with a higher level abstraction like @cristianbica says. Let's focus on that and then add a factory method.

Maybe something like `User.find(42).gid_for(:company)` would be better. As `User.find(42).company.to_gid` would still fetch and instantiate the company, IIRC.

**Comment by cristianbica** [comment]
Maybe User.find(42).company_global_id
But I would still use a GlobalID.create to avoid instantiating a model
object

**Comment by meinac** [comment]
I agree with @christianbica. User.finds(1).company_global_id would be better but create_for method is also needed For creating global id with model name and id.
I am going to implement this and add into my previous pull request. Is it ok?

**Comment by kaspth** [comment]
The only way to implement `company_global_id` is with `method_missing`. I'd love to avoid that in our `GlobalID::Identification` mixin.

Besides `method_missing` would have to check four different call types: `company_global_id`, `company_gid`, `company_signed_global_id` and `company_sgid`.

But honestly, I'm not sure which way to go. @dhh do you have any preference here?

**Comment by dhh** [comment]
I'd like to revisit the premise: `User.new(id: 4).to_global_id` results in _unnecessary object creation_.

This sounds like an unsubstantiated micro optimization. What does unnecessary mean in this context? Does it means you found AR object instantiation to be a bottleneck somewhere? Or a hot spot contributor to memory growth?

Absent of any evidence pointing to that, I don't think we need this optimization.

**Comment by cristianbica** [comment]
The optimization for getting a GID for a belongs_to comes from not hitting
the db.
There's no performance gain on a new model instance. But I would prefer to
write GlobalID.create('User', 4, options) instead of User.new(id:
4).to_global_id.
Anyway I don't have a use case where I would have an id and a class name
besides a belongs_to relation so the only thing I would implement is
getting a GID for a belongs_to without hitting the db

**Comment by dhh** [comment]
I say that just using that new instance is just fine, then, `GlobalID.create('User', 4, options)` is imo no nicer or prettier than `User.new(id: 4).to_global_id`. If anything, it's slightly more obtuse.

**Comment by kaspth** [comment]
To me, the use case is for has many associations and not belongs to associations.

@antulik's use case is having to do:

```erb
<% @favorites.each do |favorite| %>
  <%= link_to 'Share', share_path(favorite.content.to_global_id) %>
<% end %>
```

instead of just getting the gid for the content directly.

I don't have any evidence to answer your hotspot or memory growth questions, David.

**Comment by cristianbica** [comment]
Kasper haven't though of the implementation but unless we can hook into
where ActiveRecord::Relation creates the accessors then I would also avoid
method_missing and go for gid_for / sgid_for.

**Comment by dhh** [comment]
Not sure I understand the use case? Is that code snippet not possible today or it isn't desirable?

**Comment by kaspth** [comment]
It's possible, but the fetch and instantiation of the content association on favorite is the issue.

**Comment by cristianbica** [comment]
@dhh the below code would save `@favorites.count` db fetches (if content is polymorphic):
```ruby
<% @favorites.each do |favorite| %>
  <%= link_to 'Share', share_path(favorite.content_global_id) %>
<% end %>
```

**Comment by dhh** [comment]
If you're doing a piggy-back optimization, just implement content_global_id as `Content.new(id: content_id).to_global_id`?

**Comment by cristianbica** [comment]
In this example `:content` is a polymorphic association. The example is in a comment above (https://github.com/rails/globalid/issues/59#issuecomment-71363321)

**Comment by dhh** [comment]
Ah, I see. So you'd have to do `content_type.classify.new(id: content_id).to_global_id` for this optimization, yeah? Doesn't bother me greatly either, but if there was an implementation with no drawbacks, like method_missing being needed, I suppose that wouldn't offend me either.

**Comment by meinac** [comment]
There is a way to get belongs_to relations programmatically in rails
```ruby
Klass.reflect_on_all_associations(:belongs_to)
```
This will return all belongs_to relations in an array. So we can iterate it and define necessary methods on the fly with define_method. By this way we can get a gid of an object like;
```ruby
User.find(1).company_gid
```
This will only trigger one database query which for getting user object. I this this is what @cristianbica wants.
@kaspth , @dhh , @cristianbica  does this make sense?

**Comment by meinac** [comment]
But now i think this is wrong because by this way we can get belongs_to relations in run time. We need to get it on initialization time :( I think this will return empty array, right?

**Comment by cristianbica** [comment]
@meinac yes, that's true. 
@kaspth I'm not very aware of AR's internals but one way I think we could do it is to override `ActiveRecord::Associations::Builder::Association.define_readers` (from [here](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/builder/association.rb#L108)) in a mixin added to `ActiveRecord::Associations::Builder::BelongsTo`. That method would call `super` and define `name` `_global_id`/`_gid`/`_signed_global_id`/`_sgid`.

**Comment by kaspth** [comment]
@meinac how do you feel about trying @cristianbica's suggestion in your PR?

**Comment by meinac** [comment]
I'm looking into this.

**Comment by meinac** [comment]
@kaspth, I've made some changes on my pull request. You can review it.

**Comment by kaspth** [comment]
@antulik what you want can be accomplished with a simple method in your class:

```ruby
# favorite.rb
def content_global_id
  content_type.classify.new(id: content_id).to_gid
end
```

As such, we don't need to add extra complexity on GlobalID. Thanks :heart:
