### ISSUE TITLE
Can't use purpose implementation(for:)

### ISSUE THREAD

**Issue by sbhatore** [rails/globalid#62]
Hi,
    I am trying to use the purpose as specified in the readme file. 
Readme file has the folowing example given:
 
>> signup_person_sgid = Person.find(1).to_sgid(for: 'signup_form')
=> #<SignedGlobalID:0x007fea1984b520

I am trying this out in the rails 4.2.0 console. My command line is:

>>siddharth@siddharth-Inspiron-5537:~/Development/ROR/ror_2/app1$ rails console
Loading development environment (Rails 4.2.0)
irb(main):001:0> user = User.find(1).to_sgid
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
=> #<SignedGlobalID:0x007f4ba64aa2b0 @uri=#<URI::GID gid://app1/User/1>, @verifier=#<ActiveSupport::MessageVerifier:0x007f4ba5448110 @secret="\xFD7\v<\xCF\x17;Q\x0E=\x8FRzv\xD6\xE7\xAB\x98Gp\xDC\xE9\xD1\r\xC2\x87\xD1\x94 \xD5\xCDN\x04\xEB\xFDBIA\x1F\x19W\xAA\xBC\x85\xD3S>\xEF\xAA\x91\xEC\r\xF2\x0F\x1Dv\x86\xCF\xEB\xED\n\x0EJ\xC1", @digest="SHA1", @serializer=Marshal>, @purpose="default", @expires_at=Thu, 09 Apr 2015 20:04:00 UTC +00:00>
irb(main):002:0> user = User.find(1).to_sgid(for: 'signup_form')
irb(main):003:1>

User.find(1).to_sgid works well.  However, it seems using for: as a parameter is creating a loop. 
           Also expire and all other things are working fine. I only have problem with the purpose implementation here.
Maybe I am doing this incorrectly. Can someone guide me through this?

**Comment by kaspth** [comment]
The console will interpret `for:` as a for loop. Using a hash rocket will fix it on the command line `User.find(1).to_sgid(:for => 'signup_form')`

**Comment by kaspth** [comment]
Oh, and thanks for filing :heart:

**Comment by sbhatore** [comment]
Thanks for the help :)

**Comment by kaspth** [comment]
Glad it worked :wink:
