### ISSUE TITLE
Add this gem's metadata on rubygems.org

### ISSUE THREAD

**Issue by JuanitoFatas** [rails/globalid#63]
Hello globalid,

Could you please also add some metadata information of this gem in this page https://rubygems.org/gems/globalid/edit :pray::

Here are some I know:

| URL                   | VALUE                                      |
| --------------------- | ------------------------------------------ |
| **Source Code URL**   | https://github.com/rails/globalid        |
| **Documentation URL** | http://www.rubydoc.info/gems/globalid     |
| **Bug Tracker URL**   | https://github.com/rails/globalid/issues |

Thank you!

**Comment by rafaelfranca** [comment]
Done

**Comment by JuanitoFatas** [comment]
> Done

Thanks!
