### ISSUE TITLE
Improve Error When Converting Records without an Id

### ISSUE THREAD

**Issue by fny** [rails/globalid#67]
`Model.new.to_global_id` currently raises a `URI::InvalidComponentError` with the message `URI::InvalidComponentError: Expected a URI like gid://app/Person/1234: #<URI::GID gid://app>`. An error particular to `GlobalID` would be useful:

    GlobalID::UnidentifiableRecord Unable to identify #{record.class} without an id. (Maybe you forgot to call save?)

This is already being discussed in rails/rails#19861 and rails/rails#19877.

**Comment by vipulnsward** [comment]
@fny your fix looks good. Maybe send a PR, to discuss more?

**Comment by vipulnsward** [comment]
:grin: dint catch https://github.com/rails/globalid/pull/68
