### ISSUE TITLE
Stale data in ActiveJob

### ISSUE THREAD

**Issue by reichertm** [rails/globalid#76]
I have an ActiveJob created in the `after_save` callback. The job gets the instance as a parameter. Every now and then when the job executes the instance is stale - it contains the data from before the model update. I have observer in the logs that the instance is not being read from the database - it must be coming from cache. Debugging the `updated_at` column showed that the value in the Job is earlier than the the one saved in the database.

    after_save do |instance|
        SaveAttachmentsJob.perform_later(instance)
    end

    class SaveAttachmentsJob < ActiveJob::Base
      queue_as :default
    
      def perform(instance)
        # This fixes the issue.
        # instance.reload 
    
        # Every now and then this will show stale object.
        Rails.logger.info(instance.inspect)
    
        # ... some more code.
      end
    end

I have worked around the problem calling `instance.reload` in the Job.

globalid 0.3.5, active job 4.2.3, I am using Sidekiq to process the Jobs.

**Comment by reichertm** [comment]
Update:

This is most likely related to the the job running before commit: https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#cannot-find-modelname-with-id12345

I have changed the callback from `after_save` to `after_commit` and it seams to solve the issue.
Feel free to close the issue if this is intended behavior of those callbacks.

**Comment by rafaelfranca** [comment]
Yes. it is the intended behavior. Thanks
